[package]
name = "floppa-files"
version = "0.1.0"
edition = "2021"

[dependencies]
tide = "0.16" 
async-std = {version = "1.12" , features = ["attributes"]}
askama = "0.11"
nanoid = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
qrcode = "0.12"
