[package]
name = "floppa-files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tide = "0.16.0"
askama = "0.11"
async-std = {version = "1.12.0" , features = ["attributes"]}
nanoid = "0.4.0"
qrcode = "0.12.0"
image = "0.24.6"
toml = "0.7.4"
