[package]
name = "floppa_files"
version = "2.0.2"
edition = "2021"

[dependencies]
warp = "0.3.2"
tokio = { version = "1", features = ["full"] }
log = "0.4.17"
simplelog = "0.12.0"
bytes = "1.2.1"
handlebars = "4.3.4"
reqwest = "0.11.12"
nanoid = "0.4.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"
rand = "0.8.5"
humansize = "2.0.0"
